---
- hosts: all
  become: True
  vars:
    - apache_port: 80  
    - apache_deploy_path: /var/www/html
    - apache_conf_path: /etc/httpd/conf    
  tasks:
    - name: Install Apache Server
      yum: 
        name: httpd
        state: present
    - name: Enable on Reboot
      service: 
        name: httpd
        enabled: True
    - name: Start Apache Server
      service:
        name: httpd
        state: started
    - name: Copy File from Control Machine to Apache Server
      copy:
        src: index.html
        dest: "{{apache_deploy_path}}/index.html"
      notify:
          - Restart Apache  
    - name: Change the Port Number
      template:
        src: httpd.conf
        dest: "{{apache_conf_path}}/httpd.conf"
      notify:
          - Restart Apache
  handlers: 
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
