---
- hosts: all
  become: True
  tasks: 
    - name: Install Git
      yum:
        name: git
        state: absent
      when: 
       - ansible_os_family=="Debian"
       - ansible_distribution_major_version=="6" 
