---
- hosts: all
  become: True
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Start Nginx
      service:
         name: nginx
         state: started
    - name: Insert Index Pages
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
