---
- hosts: all
  become: True
  serial: 
  - 1
  - "20%"
  tasks:
    - name: Install Git
      debug:
        msg: Installing Git
      tags:
        - install
    - name: Setup Environment
      debug:
        msg: Environment Setup
      tags:
        - Setup
    - name: Configuration 
      debug:
        msg: System Configuration
      tags:
        - config
    - name: Deploy to Server
      debug:
        msg: Deploying to the Server
      tags:
        - deploy


